### ISSUE TITLE
Requirements error upon pip install

### ISSUE THREAD

**Issue by miramou** [xuesoso/nheatmap#1]
Hi! When installing nheatmap through pip, I believe one package is missing from the requirements. I can reproduce the error by creating a conda environment using the yaml file below. 

![Screen Shot 2020-08-26 at 2 06 45 PM](https://user-images.githubusercontent.com/27246693/91345717-6ba7ca80-e7a5-11ea-8518-80ba6edc8563.png)

This produces the following error message.

![Screen Shot 2020-08-26 at 1 58 49 PM](https://user-images.githubusercontent.com/27246693/91345189-99d8da80-e7a4-11ea-88c0-ed63ebb1c475.png)

I can resolve the error by amending the yaml file to also request that it pip install "packaging" as seen below. 

![Screen Shot 2020-08-26 at 2 07 28 PM](https://user-images.githubusercontent.com/27246693/91345763-7febc780-e7a5-11ea-80ca-1b2981c0a7ed.png)

I think this a quick fix and would only require adding another requirement check. Thanks!

**Comment by xuesoso** [comment]
Thanks for raising the issue. Update v 0.1.4 has added "packaging" as a required dependecy.
