### ISSUE TITLE
Attribute error in tutorial 

### ISSUE THREAD

**Issue by michael-swift** [xuesoso/nheatmap#2]
Hi Xuesoso, 

I am running your very fine package named nheatmap. As i run to tutorial to get my bearings on the software package installed via the pip command line tool, I run into this attribute error. 

`g = nhm(data=df, dfr=dfr, dfc=dfc, figsize=(10, 10), linewidths=0, showxticks=False, cmaps=cmaps)
fig, plots = g.run()`

"module 'matplotlib.ticker' has no attribute '_mathdefault'"

let me know if this is reproducible for you

**Comment by xuesoso** [comment]
Hi michael-swift,

Can you share with me your matplotlib and nheatmap versions?

**Comment by michael-swift** [comment]
I am using matplotlib-base 3.2.2

**Comment by xuesoso** [comment]
can you tell me the output of:

```python
from nheatmap import nhm
nhm.__version__
```

**Comment by michael-swift** [comment]
That gives me AttributeError: type object 'nheatmap' has no attribute '__version__'
I did:
pip install nhm 

About 2 days ago if that's the information you're after?

**Comment by xuesoso** [comment]
another way to get the version is to execute the following in your terminal
```bash
pip list | grep 'nheatmap'
```
if it's up to date, it should say "nheatmap 0.1.4"

if it's out-dated, then execute the following in terminal
```bash
pip install --upgrade nheatmap
``` 

It should solve your issues. Let me know if it works.

**Comment by michael-swift** [comment]
Looks great now! I had indeed somehow grabbed 0.1.2, in that version the colorbar for the heatmaps wouldn't show, but now it does!
