### ISSUE TITLE
change heatmap cmap

### ISSUE THREAD

**Issue by sevahn** [xuesoso/nheatmap#3]
in the cmaps argument, is there a way to specify the color palette used for the heat map itself (e.g. specify a palette beyond "viridis")?

**Comment by xuesoso** [comment]
oh yeah, so to do that, just specify "cmapCenter", for example:

```python
import nheatmap as nhm
fig = nhm(df, cmapCenter='viridis')
```

**Comment by xuesoso** [comment]
An example has now been included in the tutorial to showcase how to change the colormap for the center heatmap.
