### ISSUE TITLE
specify cbar range for the main heatmap

### ISSUE THREAD

**Issue by sevahn** [xuesoso/nheatmap#4]
is there a way to specify the range of the cbar as in the [vmin and vmax args in seaboarn](https://seaborn.pydata.org/generated/seaborn.heatmap.html)?

**Comment by xuesoso** [comment]
Yes, you can specify the range of values for the center heatmap like so:

```
g = nhm(data=df)
fig, plots = g.run(center_args={'max':5, 'min':0})
```

here, 'max' and 'min' correspond to 'vmax' and 'vmin' in seaborn, respectively.
